version: "3.7"
services:
  db:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - postgres.env
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - network

  api:
    build: ./api
    restart: on-failure:1
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    environment:
      PG_HOST: db
    env_file:
      - api.env
      - postgres.env
    command: ["uvicorn", "api.app:prod_app", "--host", "0.0.0.0"]
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge

volumes:
  postgres_data:
